# Generated by Django 5.2 on 2025-05-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_login_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='name_of_topic',
        ),
    ]
