# Generated by Django 5.2 on 2025-05-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_name_room_name_of_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
