# Generated by Django 5.2 on 2025-05-31 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='name_of_topic',
            new_name='name',
        ),
    ]
