# Generated by Django 5.1.7 on 2025-06-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
